config_ip = ""
config_port = 25565
config_command_prefix = "."
config_admin_users = [123456, 465789]
config_superadmin_users = [123456]
config_ping_time = 30
config_discord_token = ""
config_panel_token = ""
config_panel_url = ""
config_server_id = ""
config_custom_footer = "Server:  | Modpack: "
config_embed_color = 0xa15600
config_votes_needed = 2
config_vote_timeout = 60
config_server_auto_time = 10
